version: "3.9"
services:
  app-service:
    image: jasonpark94/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it 
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
  auth-service:
    image: jasonpark94/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"