version: "3.9"
services:
  app-service:
    image: jasonpark94/app-service # specify name of image on Docker Hub
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: jasonpark94/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET} # New!
    ports:
      - "3000:3000"